# Form implementation generated from reading ui file 'New_Gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    """
    Class that runs the Gui
    """
    def setupUi(self, MainWindow) -> None:
        """
        Function that sets up the gui and inputs
        :param MainWindow: The main window for the gui
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(457, 394)
        MainWindow.setMinimumSize(QtCore.QSize(457, 394))
        MainWindow.setMaximumSize(QtCore.QSize(457, 394))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.Voting_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Voting_label.setGeometry(QtCore.QRect(120, 10, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Voting_label.setFont(font)
        self.Voting_label.setObjectName("Voting_label")
        self.ID_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ID_label.setGeometry(QtCore.QRect(50, 70, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ID_label.setFont(font)
        self.ID_label.setObjectName("ID_label")
        self.ID_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ID_input.setGeometry(QtCore.QRect(110, 70, 261, 41))
        self.ID_input.setObjectName("ID_input")
        self.candidates_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidates_label.setGeometry(QtCore.QRect(140, 120, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.candidates_label.setFont(font)
        self.candidates_label.setObjectName("candidates_label")
        self.button_jade = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.button_jade.setGeometry(QtCore.QRect(180, 170, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_jade.setFont(font)
        self.button_jade.setObjectName("button_jade")
        self.button_cass = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.button_cass.setGeometry(QtCore.QRect(180, 210, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.button_cass.setFont(font)
        self.button_cass.setObjectName("button_cass")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(120, 260, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.message_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.message_label.setGeometry(QtCore.QRect(0, 310, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.message_label.setFont(font)
        self.message_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.message_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.message_label.setObjectName("message_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 457, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow) -> None:
        """
        Function that translates the UI
        :param MainWindow: The main window for the gui
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Voting_label.setText(_translate("MainWindow", "VOTING APPLICATION"))
        self.ID_label.setText(_translate("MainWindow", "ID"))
        self.candidates_label.setText(_translate("MainWindow", "CANDIDATES"))
        self.button_jade.setText(_translate("MainWindow", "Jade"))
        self.button_cass.setText(_translate("MainWindow", "Cass"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT VOTE"))
        self.message_label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
